#ifndef COMMON_H
#define COMMON_H


#define SCREEN_WIDTH  1000
#define SCREEN_HEIGHT 700

#define SCREEN_SEARCH_LE_WIDTH 200
#define SCREEN_SEARCH_LE_HEIGHT 30
#define SCREEN_SEARCH_BTN_WIDTH 30
#define SCREEN_SEARCH_BTN_HEIGHT SCREEN_SEARCH_LE_HEIGHT

#define SCREEN_TOP_HEIGHT (SCREEN_HEIGHT/10)



#endif // COMMON_H
